name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [13.12.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}

      - run: node -v
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
